name: Build B3

on:
  push:
    tags:
      - 'v*'

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install maturin pytest

      - name: Build and Test 
        working-directory: ./task_b3
        run: |
          maturin develop
          pytest